
version: 0.0
os: linux
files:
  - source: /analytic-server
    destination: /var/www/analytic-server
  - source: /analytic_server.conf
    destination: /etc/apache2/sites-available
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300

  BeforeInstall:
    - location: scripts/install_dependencies

  AfterInstall:
    - location: scripts/setup_virtualenv
    - location: scripts/start_server
      timeout: 300
